/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnnotationTool: typeof import('./components/AnnotationTool.vue')['default']
    BadgesGroup: typeof import('./components/BadgesGroup.vue')['default']
    ConnectivityInfo: typeof import('./components/ConnectivityInfo.vue')['default']
    DatasetCard: typeof import('./components/DatasetCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconArrowDown: typeof import('@element-plus/icons-vue')['ArrowDown']
    ElIconArrowLeft: typeof import('@element-plus/icons-vue')['ArrowLeft']
    ElIconArrowRight: typeof import('@element-plus/icons-vue')['ArrowRight']
    ElIconDelete: typeof import('@element-plus/icons-vue')['Delete']
    ElIconLocation: typeof import('@element-plus/icons-vue')['Location']
    ElIconWarning: typeof import('@element-plus/icons-vue')['Warning']
    ElIconWarnTriangleFilled: typeof import('@element-plus/icons-vue')['WarnTriangleFilled']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ImageGallery: typeof import('./components/ImageGallery.vue')['default']
    SearchFilters: typeof import('./components/SearchFilters.vue')['default']
    SearchHistory: typeof import('./components/SearchHistory.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SidebarContent: typeof import('./components/SidebarContent.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
